name: ci

on:
    push:

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Build image
              run: |
                ./scripts/update.sh
